### ISSUE TITLE
Write out order that checks need to be made

### ISSUE THREAD

**Issue by SMLM42** [SMLM42/BCP_Project#2]

**Comment by SMLM42** [comment]
Step 1: Split up string into its component detachments
Step 2: Find the 1-3 Faction ids for each detachments, if allowed combination then continue
Step 3: Check that each detachment has the required CP, PL and Pts at top
Step 4: Check each detachment for whether it has the required minimum number of units and doesnt exceed the maximum number of units.

**Comment by SMLM42** [comment]
Things that will need to exist:
Faction array of all factions
Templates of each detachment to compare against

**Comment by luvkylo** [comment]
Step 1 should be check if all string exist, i.e. detachements' array length is <= some number
